node_name "retro-pie"
checksum_path    "/var/chef/checksums"
cookbook_path    "/var/chef/cookbooks"
file_backup_path "/var/chef/backup"
file_cache_path  "/var/chef/cache"
role_path        "/var/chef/roles"
json_attribs nil
lockfile nil
log_level :info
log_location STDOUT
solo true
